### ISSUE TITLE
cant build

### ISSUE THREAD

**Issue by HippieWithGuns** [WesR/Light-Toggle#1]
i cant build this version. see below.
can you help? i understand basic C (can code microcontroller) but i really dont get this one^^

![image](https://cloud.githubusercontent.com/assets/6748508/9992866/effecdfa-6074-11e5-979a-8ae5a1a6b6c9.png)

**Comment by WesR** [comment]
It looks like your trying to compile for both aplite and basalt. Since pins are only on the time you need to use basalt. If your not, also make sure your using os 3.

**Comment by HippieWithGuns** [comment]
i found it out.
had to put in uint_16 as datatype for the service id in the avaiability handler and its prototype.
thanks anyway for your great opensource code and help. really appreciate this:)

**Comment by WesR** [comment]
No problem! I'm glad I can help, though I don't feel like I did much here!
